
server:
  servlet:
    context-path: /
  ssl:
    key-alias: tomcat
    key-store: classpath:keystoreOnline.p12
    key-store-password: gujian1002
    key-store-type: PKCS12
  port: 8443

spring:
  application:
      name: debit

  redis:
      host: 101.132.109.136
      password: gujian
      port: 6379
      jedis:
        max-idle: 100
        min-idle: 8
        max-active: 10
        max-wait: -1
      timeout: 3000

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.gzw.debit.dal.model
  config-location: classpath:mybatis/mybatis-config.xml
