
server:
  servlet:
    context-path: /
  ssl:
    key-alias: tomcat
    key-store: classpath:keystore.p12
    key-store-password: gujian1002
    key-store-type: PKCS12
  port: 8443

spring:
  #mysql
  datasource:
      url: jdbc:mysql://101.132.109.136:3306/debit?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 101.132.109.136
    password: gujian
    port: 6379
    jedis:
      max-idle: 100
      min-idle: 8
      max-active: 10
      max-wait: -1
    timeout: 3000

  application:
      name: debit
  resources:
    static-locations: classpath:static

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.gzw.debit.dal.model
  config-location: classpath:mybatis/mybatis-config.xml

# redis
#redis
#jedis:
#  pool:
#    host: 101.132.109.136
#    port: 6379
#    timeout: 2000
#    password: gujian
#    config:
#      maxTotal: 10
#      maxIdle: 100
#      maxWaitMillis: -1

#redis

